# SQL Database Connection
#DataBase Driver
# Hibernate dialect for SQLite
# Automatic schema update

spring.datasource.url=jdbc:sqlite:Ecom.db
spring.datasource.driver-class-name=org.sqlite.JDBC
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
spring.jpa.hibernate.ddl-auto=update

# Disable the H2 console
spring.h2.console.enabled=false

# Server Configuration
server.port=8000

# JWT Configuration
jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
jwt.expiration=86400000

# Enable CORS
spring.mvc.cors.allowed-origins=http://localhost:3000
spring.mvc.cors.allowed-methods=GET,POST,PUT,DELETE,OPTIONS
spring.mvc.cors.allowed-headers=*
spring.mvc.cors.allow-credentials=true

# Hibernate Configuration
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Enable SQL initialization
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true

# H2 Console Configuration
spring.h2.console.settings.web-allow-others=true

# Security Configuration
spring.security.user.name=user
spring.security.user.password=password

# Logging configuration
logging.level.com.TDD.Ecom=DEBUG
logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.web=DEBUG

